;;; templates.el -*- lexical-binding: t; -*-

(defun template ()
  (interactive)
  (setq rating (read-string "Rating: "))
  (setq name (read-string "Directory name: "))
  (setq rating-dir (concat "~/projects/cp/" rating))
  (setq dir (concat rating-dir "/" name))
  (unless (file-exists-p rating-dir)
    (make-directory rating-dir t))
  (copy-directory "~/projects/cp/template" dir)
  (delete-other-windows)
  (find-file (concat dir "/" "input.txt"))
  (evil-window-vsplit)
  (find-file (concat dir "/" "main.cpp")))
